[phases.setup]
nixPkgs = ["node", "chromium", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "mesa", "gbm", "alsa-lib"]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "PUPPETEER_EXECUTABLE_PATH=$(which chromium) node bot.js"
